# OpenTelemetry Operator
# Helm chart: open-telemetry/opentelemetry-operator
# Docs: https://opentelemetry.io/docs/platforms/kubernetes/operator/

manager:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

# Enable auto-instrumentation webhook
admissionWebhooks:
  certManager:
    enabled: true

# Feature gates
featureGates: "+operator.autoinstrumentation.go,+operator.autoinstrumentation.nginx"
